package com.faeryware.launcher;

import android.app.*;import android.app.role.RoleManager;import android.appwidget.AppWidgetManager;import android.content.*;import android.content.pm.ResolveInfo;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public final class FaerywareLauncherActivity extends Activity {
  private static final int HOME=0,FEED=1,HOUSE=2,APPS=3; private int page=HOME; private LinearLayout root; private GestureDetector gestures; private android.content.SharedPreferences prefs;
  public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SHOW_WALLPAPER);prefs=getSharedPreferences(FaerywareMemoryStore.PUBLIC_PREFS,MODE_PRIVATE);if(!prefs.contains(FaerywareMemoryStore.KEY_CONTEXT_MODE))prefs.edit().putBoolean(FaerywareMemoryStore.KEY_CONTEXT_MODE,true).apply();gestures=new GestureDetector(this,new GestureDetector.SimpleOnGestureListener(){public boolean onDown(MotionEvent e){return true;}public boolean onFling(MotionEvent a,MotionEvent b,float vx,float vy){if(a==null||b==null||getCurrentFocus() instanceof EditText)return false;float dx=b.getX()-a.getX(),dy=b.getY()-a.getY();if(Math.abs(dx)>Math.abs(dy)&&Math.abs(dx)>dp(80))page=dx>0?FEED:HOUSE;else if(Math.abs(dy)>dp(90))page=dy<0?APPS:HOME;else return false;render();return true;}});render();}
  public boolean dispatchTouchEvent(MotionEvent e){if(gestures!=null)gestures.onTouchEvent(e);return super.dispatchTouchEvent(e);} protected void onResume(){super.onResume();render();}

  private void render(){int f=fae();ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(Color.argb(220,4,4,10));LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);ImageView hero=new ImageView(this);hero.setScaleType(ImageView.ScaleType.CENTER_INSIDE);hero.setImageBitmap(FaerywareChibiRenderer.render(this,f,dp(256)));hero.setAlpha(page==HOME?.9f:.55f);shell.addView(hero,new LinearLayout.LayoutParams(-1,dp(page==HOME?260:150)));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(42));shell.addView(root);s.addView(shell);header();if(page==HOME)home();else if(page==FEED)feed();else if(page==HOUSE)house();else apps();root.addView(txt("→ HAUNT FEED   ← HOUSE   ↑ APPS   ↓ HOME",10,Color.LTGRAY,true),top(24));setContentView(s);}
  private void header(){int f=fae();root.addView(txt("FAERYWARE",30,Color.WHITE,true));root.addView(txt("ANDROID HAS DEVELOPED A SMALL TENANT PROBLEM",11,FaerywareMemoryStore.faeColor(f),true),top(2));root.addView(txt(FaerywareMemoryStore.faeStamp(f)+" • "+FaerywareMemoryStore.summary(this),10,0xffc4c4dc,false),top(5));}
  private void home(){int f=fae(),c=FaerywareMemoryStore.faeColor(f);TextView h=txt(FaerywareMemoryStore.faeStamp(f)+"\n"+FaerywareMemoryStore.whisper(this,f)+"\n\nHAUNT LEVEL: "+prefs.getString("haunt","HAUNTED")+"\n"+FaerywareMemoryStore.summary(this),20,Color.WHITE,true);h.setGravity(Gravity.CENTER);h.setPadding(dp(12),dp(26),dp(12),dp(26));h.setBackgroundColor(Color.argb(145,Color.red(c),Color.green(c),Color.blue(c)));root.addView(h,top(12));search(false);GridLayout g=grid();g.addView(btn("HAUNT FEED",v->{page=FEED;render();}));g.addView(btn("GHOST HOUSE",v->{page=HOUSE;render();}));g.addView(btn("APPS",v->{page=APPS;render();}));g.addView(btn("SUMMON RESIDENTS",v->summon()));g.addView(btn("MORE HAUNTED",v->more()));g.addView(btn("HAUNT CONSOLE",v->startActivity(new Intent(this,FaerywareHauntConsoleActivity.class))));g.addView(btn("BECOME HOME",v->becomeHome()));g.addView(btn("FOLLOW PHONE CONTEXT",v->goblin(FaerywareGoblinOverlayService.ACTION_FOLLOW_CONTEXT)));root.addView(g,top(12));dock();}
  private void feed(){int f=fae();root.addView(txt("HAUNT FEED",25,FaerywareMemoryStore.faeColor(f),true),top(14));root.addView(txt("RIGHT NOW\n"+FaerywareMemoryStore.faeStamp(f)+"\n"+FaerywareMemoryStore.summary(this)+"\n"+FaerywareMemoryStore.whisper(this,f),12,Color.WHITE,false),top(8));EditText n=new EditText(this);n.setHint("leave a note for whatever lives in the phone...");n.setHintTextColor(Color.GRAY);n.setTextColor(Color.WHITE);n.setText(prefs.getString("scratchpad",""));n.setMinLines(4);n.setOnFocusChangeListener((v,x)->{if(!x)prefs.edit().putString("scratchpad",n.getText().toString()).apply();});root.addView(n,top(10));root.addView(btn("SAVE SCRATCHPAD",v->{prefs.edit().putString("scratchpad",n.getText().toString()).apply();Toast.makeText(this,"The house remembers.",Toast.LENGTH_SHORT).show();}),top(4));search(false);dock();}
  private void house(){int f=fae();root.addView(txt("GHOST HOUSE",25,Color.WHITE,true),top(14));root.addView(txt("RESIDENT STATUS\n"+FaerywareMemoryStore.faeStamp(f)+" • "+prefs.getString("haunt","HAUNTED")+"\n"+FaerywareMemoryStore.summary(this),12,FaerywareMemoryStore.faeColor(f),true),top(8));GridLayout g=grid();g.addView(btn("HAUNT CONSOLE",v->startActivity(new Intent(this,FaerywareHauntConsoleActivity.class))));g.addView(btn("SUMMON RESIDENTS",v->summon()));g.addView(btn("BANISH RESIDENTS",v->goblin(FaerywareGoblinOverlayService.ACTION_BANISH)));g.addView(btn("MORE HAUNTED",v->more()));g.addView(btn("LIVE WALLPAPER",v->wallpaper()));g.addView(btn("PIN WIDGET",v->pinWidget()));g.addView(btn("OVERLAY PERMISSION",v->safe(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())))));g.addView(btn("APP AWARENESS",v->safe(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))));g.addView(btn("NOTIFICATION AWARENESS",v->safe(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS))));g.addView(btn("RETURN TO ONE UI",v->safe(new Intent(Settings.ACTION_HOME_SETTINGS))));root.addView(g,top(10));root.addView(txt("AWARENESS BOUNDARY\nForeground-app awareness stores package/app label only. Notification awareness stores source app + time only. No keystrokes, message bodies, passwords, or view text are copied.",10,0xffbdbdd3,false),top(14));}
  private void apps(){root.addView(txt("APP CATACOMBS",25,Color.WHITE,true),top(14));EditText q=search(true);GridLayout g=new GridLayout(this);g.setColumnCount(3);root.addView(g,top(6));List<ResolveInfo> all=launcherApps();Runnable paint=()->{g.removeAllViews();String x=q.getText().toString().trim().toLowerCase(Locale.US);for(ResolveInfo r:all){if(r.activityInfo==null)continue;String l=String.valueOf(r.loadLabel(getPackageManager()));if(!x.isEmpty()&&!l.toLowerCase(Locale.US).contains(x))continue;g.addView(btn(l,v->launch(r)));}};q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){paint.run();}public void afterTextChanged(android.text.Editable e){}});paint.run();}
  private EditText search(boolean local){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);EditText q=new EditText(this);q.setHint(local?"filter installed apps":"search apps or the web");q.setTextColor(Color.WHITE);q.setHintTextColor(Color.GRAY);row.addView(q,new LinearLayout.LayoutParams(0,-2,1));if(!local)row.addView(btn("WEB",v->{String x=q.getText().toString().trim();if(!x.isEmpty())safe(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+Uri.encode(x))));}));root.addView(row,top(10));return q;}
  private void dock(){GridLayout g=grid();g.addView(btn("☎ PHONE",v->safe(new Intent(Intent.ACTION_DIAL))));g.addView(btn("✉ MESSAGES",v->safe(new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:")))));g.addView(btn("◉ CAMERA",v->safe(new Intent(android.provider.MediaStore.INTENT_ACTION_STILL_IMAGE_CAMERA))));g.addView(btn("◎ BROWSER",v->safe(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com")))));root.addView(g,top(14));}

  private void summon(){if(!Settings.canDrawOverlays(this)){safe(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));return;}prefs.edit().putBoolean(FaerywareMemoryStore.KEY_RESIDENT_ENABLED,true).apply();goblin(FaerywareGoblinOverlayService.ACTION_SUMMON);}
  private void more(){String x=prefs.getString("haunt","HAUNTED"),n="CALM".equals(x)?"HAUNTED":("HAUNTED".equals(x)?"FERAL":"CALM");prefs.edit().putString("haunt",n).apply();if(Settings.canDrawOverlays(this))goblin(FaerywareGoblinOverlayService.ACTION_REFRESH);Toast.makeText(this,"HAUNT LEVEL → "+n,Toast.LENGTH_SHORT).show();render();}
  private void goblin(String a){Intent i=new Intent(this,FaerywareGoblinOverlayService.class).setAction(a);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception e){Toast.makeText(this,"Android held the goblin at the boundary.",Toast.LENGTH_SHORT).show();}}
  private void becomeHome(){if(Build.VERSION.SDK_INT>=29){RoleManager r=getSystemService(RoleManager.class);if(r!=null&&r.isRoleAvailable(RoleManager.ROLE_HOME)){safe(r.createRequestRoleIntent(RoleManager.ROLE_HOME));return;}}safe(new Intent(Settings.ACTION_HOME_SETTINGS));}
  private void wallpaper(){try{Intent i=new Intent(WallpaperManager.ACTION_CHANGE_LIVE_WALLPAPER);i.putExtra(WallpaperManager.EXTRA_LIVE_WALLPAPER_COMPONENT,new ComponentName(this,FaerywareWallpaperService.class));startActivity(i);}catch(Exception e){safe(new Intent(WallpaperManager.ACTION_LIVE_WALLPAPER_CHOOSER));}}
  private void pinWidget(){AppWidgetManager m=AppWidgetManager.getInstance(this);if(Build.VERSION.SDK_INT>=26&&m.isRequestPinAppWidgetSupported())m.requestPinAppWidget(new ComponentName(this,FaerywareWidgetProvider.class),null,null);}
  private List<ResolveInfo> launcherApps(){Intent i=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> r=new ArrayList<>(getPackageManager().queryIntentActivities(i,0));r.removeIf(x->x.activityInfo==null||getPackageName().equals(x.activityInfo.packageName));r.sort(Comparator.comparing(x->String.valueOf(x.loadLabel(getPackageManager())),String.CASE_INSENSITIVE_ORDER));return r;}
  private void launch(ResolveInfo r){if(r.activityInfo==null)return;safe(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER).setComponent(new ComponentName(r.activityInfo.packageName,r.activityInfo.name)).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));}
  private void safe(Intent i){try{startActivity(i);}catch(Exception e){Toast.makeText(this,"Android has no handler for that route.",Toast.LENGTH_SHORT).show();}}
  private int fae(){return FaerywareMemoryStore.activeFaeIndex(this);} private GridLayout grid(){GridLayout g=new GridLayout(this);g.setColumnCount(2);g.setUseDefaultMargins(true);return g;} private Button btn(String s,View.OnClickListener l){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(10.5f);b.setOnClickListener(l);return b;} private TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(t.getTypeface(),1);return t;} private LinearLayout.LayoutParams top(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
